# Uncomment the next line to define a global platform for your project
platform:ios,'9.0'
use_frameworks!

target 'FMiddleLevelDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FMiddleLevelDemo

  pod 'FMiddleLevel',  :path => '../'
  
  pod 'KCHomePageModule',  :path => '../OherModel/KCHomePageModule'
  
  target 'FMiddleLevelDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FMiddleLevelDemoUITests' do
    # Pods for testing
  end

end
